### ISSUE TITLE
Unnecessary steps in “unify more”

### ISSUE THREAD

**Issue by cionx** [cs3110/textbook-solutions#10]
I believe the solution to “unify more” should end sooner:

https://github.com/cs3110/textbook-solutions/blob/b91186d27bf29dec75b44f055ff65c3430d7b96c/chapter9.ml#L806-L811

The substitution `(U -> W)/Z` stems from the equation `Z = U -> W`, so we need to remove this equation before applying the substitution. This leads to the following steps instead:
```
       = unify({ Z = U -> W })
        which is equal to U''';{| (U -> W)/Z |}, where U''' is
         unify({| (U -> W)/Z |}{})
         = unify({})
         = {| |} (the empty substitution)
```

For comparison, here is how the solution to the previous exercise (“unify”) ends:

https://github.com/cs3110/textbook-solutions/blob/b91186d27bf29dec75b44f055ff65c3430d7b96c/chapter9.ml#L783-L788

**Comment by clarksmr** [comment]
Thank you! Yes, those two exercises both had rather bloated solutions. I've streamlined them.
