### ISSUE TITLE
Specify type in solution to "functorized BST"

### ISSUE THREAD

**Issue by cionx** [cs3110/textbook-solutions#14]
The current solution to "functorized BST":

https://github.com/cs3110/textbook-solutions/blob/20ea1b9824beb4c3e408b749adca6f751dd1d626/chapter8.ml#L296-L367

I don’t understand how one is supposed to create a non-empty set with this solution. As an example, I tried to create a set of integers:
```ocaml
module Int = struct
  type t = int
  let compare = Stdlib.compare
end

module IntSet = BstSet (Int)
let set = IntSet.empty |> IntSet.insert 1
```
But the last line fails:
```text
let set = IntSet.empty |> IntSet.insert 1
                                        ^
Error: This expression has type int but an expression was expected of type
         IntSet.elt
```
From what I understand, the problem is that the definition of `IntSet.elt` is encapsulated. And as far as I can tell, this means that we cannot create actual values of this type, and thus cannot insert anything into the empty set.

It seems to me that this problem is also adressed in the textbook:

> ### 5.9.3.3 How `Map` Uses Module Type Constraints
> In the standard library’s `map.mli` interface, the specification for `Map.Make` is:
> ```ocaml
> module Make (Ord : OrderedType) : S with type key = Ord.t
> ```
> The `with` constraint there is crucial. Recall that type constraints specialize a module type. Here, `S with type key = Ord.t` specializes `S` to expose the equality of `S.key` and `Ord.t`. In other words, the type of keys is the ordered type.

So it seems to me that we need to extend the line
```ocaml
module BstSet (Ord : Ordered) : Set = struct
```
to
```ocaml
module BstSet (Ord : Ordered) : Set with type elt = Ord.t = struct
```
I tested this modified code with my above example, and it makes the example work as expected.

**Comment by clarksmr** [comment]
Thanks!
