### ISSUE TITLE
Bugs in the solutions of insert_after and insert_before

### ISSUE THREAD

**Issue by ishwar00** [cs3110/textbook-solutions#4]
https://github.com/cs3110/textbook-solutions/blob/80d164a4c0121cf6559b0880277ab255bc44c72a/chapter7.ml#L188-L202

The solution has the following problems:
- It will never raise the `Not_found` exception, the reason for that is, in the body of the `while` loop, `!m` will never be `None`.
- It fails to add `n2` after `n1` every time except when `n1` is the only node present in the list, it happens because the `structural equality` test on line 195 https://github.com/cs3110/textbook-solutions/blob/80d164a4c0121cf6559b0880277ab255bc44c72a/chapter7.ml#L194-L196
- It does not address the case when `n1` is the last node.
- After inserting(assume it does) node `n2` after `n1`, it does not stop.

`insert_before` also has similar bugs.
https://github.com/cs3110/textbook-solutions/blob/80d164a4c0121cf6559b0880277ab255bc44c72a/chapter7.ml#L203-L217

**Comment by ishwar00** [comment]
PR #3 resolves the bugs.

**Comment by clarksmr** [comment]
Mitigated by b91186d
