### ISSUE TITLE
remove does not work on lists with multiple nodes

### ISSUE THREAD

**Issue by ishwar00** [cs3110/textbook-solutions#5]
https://github.com/cs3110/textbook-solutions/blob/80d164a4c0121cf6559b0880277ab255bc44c72a/chapter7.ml#L218-L234

It has the following bugs:
- Never raises the `Not_found` exception
- Does not work on lists containing more than one node.
refer issue #4 to understand bugs.

**Comment by ishwar00** [comment]
PR #3 fixes bugs.

**Comment by clarksmr** [comment]
Mitigated by b91186d
