### ISSUE TITLE
Missing big-step in “let and match expressions”

### ISSUE THREAD

**Issue by cionx** [cs3110/textbook-solutions#9]
I believe the following line may not be entirely correct:

https://github.com/cs3110/textbook-solutions/blob/b91186d27bf29dec75b44f055ff65c3430d7b96c/chapter9.ml#L608

From what I understand, we cannot directly big-step a `Left` expression, but need to do the following instead:
```
    because <[], Left 2> ==> Left 2                           (Left)
      because <[], 2> ==> 2                                   (const)
```

This is based on the following rule for big-stepping `Left` expressions from (subsection 9.4.5 of) the textbook:
```
<env, Left e> ==> Left v
  if <env, e> ==> v
```

**Comment by clarksmr** [comment]
Thank you!
